name: Version Management

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment version
        id: increment_version
        run: |
          if [ ! -f Version.txt ]; then
            echo "Version.txt not found! Exiting."
            exit 1
          fi
          current_version=$(cat Version.txt)
          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo $new_version > Version.txt
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add Version.txt
          git commit -m "Increment version to $new_version"
          git tag "v$new_version"
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
